ACTION_IMPORT = "import"
ACTION_LIST = [ACTION_IMPORT]

SOURCE_CSE = "cse" # Component Search engine
SOURCE_EEC = "eec" # EE Concierge
SOURCE_SNAP = "snap" # SnapEDA
SOURCE_LIST = [SOURCE_CSE, SOURCE_EEC, SOURCE_SNAP]
SOURCE_DEFAULT = SOURCE_CSE

SYMBOL_EXTENSIONS = ["kicad_sym"]
FOOTPRINT_EXTENSIONS = ["kicad_mod"]
MODEL_EXTENSIONS = ["stp", "step"]